"""Tests for can_detect/config.py: no defaults, ranges, copy, checksums.

The properties worth holding on to are the ones a later session depends on. A
parameter absent from the file has to stop the session and name itself, because
the alternative is a table in the thesis produced with a window length nobody
recorded. A value outside its range has to do the same. The copy stored with the
results has to be the file that was read, comments included. And the digests have
to match the bytes of the files actually used, because criteria 3.7 and 9.5
decide from them whether two sessions are comparable.

Usage, from the repository root:
    powershell -ExecutionPolicy Bypass -File tests/run_tests.ps1
    python3 tests/test_config.py
"""

from __future__ import annotations

import hashlib
import sys
import tempfile
import unittest
from pathlib import Path

TOOLS_DIR = (Path(__file__).resolve().parents[2] / "tools")
if str(TOOLS_DIR) not in sys.path:
    sys.path.insert(0, str(TOOLS_DIR))

from can_detect import config  # noqa: E402
from can_detect import session as session_names  # noqa: E402

COMPLETE = {
    "dbc_path": ["bus1.dbc", "bus2.dbc"],
    "baseline_path": "reference.profile",
    "window_s": "1.0",
    "sigma_multiplier": "3.0",
    "missing_frame_multiplier": "3.0",
    "min_interval_observations": "100",
    "burst_min_frames": "5",
    "burst_interval_factor": "0.5",
    "match_tolerance_s": "1.0",
    "random_seed": "20260919",
}


def render(values: dict) -> str:
    lines = ["# generated by the test suite"]
    for name, value in values.items():
        for item in (value if isinstance(value, list) else [value]):
            lines.append(f"{name} = {item}")
    return "\n".join(lines) + "\n"


class ConfigCase(unittest.TestCase):
    """Base class giving each test a directory with the input files in place."""

    def setUp(self) -> None:
        self._tmp = tempfile.TemporaryDirectory()
        self.dir = Path(self._tmp.name)
        self.addCleanup(self._tmp.cleanup)
        for name in ("bus1.dbc", "bus2.dbc"):
            (self.dir / name).write_text(f"BO_ 1 {name}\n", encoding="utf-8")
        (self.dir / "reference.profile").write_text("# profile\n",
                                                    encoding="utf-8")

    def write(self, values: dict, name: str = "session.conf") -> Path:
        path = self.dir / name
        path.write_text(render(values), encoding="utf-8")
        return path

    def variant(self, **overrides) -> dict:
        values = dict(COMPLETE)
        values.update(overrides)
        return values


class CompleteFile(ConfigCase):
    def test_every_parameter_is_read_with_its_own_type(self) -> None:
        session = config.load_config(self.write(COMPLETE))

        self.assertEqual(session.window_s, 1.0)
        self.assertEqual(session.sigma_multiplier, 3.0)
        self.assertEqual(session.missing_frame_multiplier, 3.0)
        self.assertEqual(session.match_tolerance_s, 1.0)
        self.assertEqual(session.min_interval_observations, 100)
        self.assertEqual(session.burst_min_frames, 5)
        self.assertEqual(session.burst_interval_factor, 0.5)
        self.assertEqual(session.random_seed, 20260919)
        for name in ("min_interval_observations", "burst_min_frames",
                     "random_seed"):
            self.assertIsInstance(getattr(session, name), int, name)
        for name in ("window_s", "sigma_multiplier",
                     "missing_frame_multiplier", "match_tolerance_s"):
            self.assertIsInstance(getattr(session, name), float, name)

    def test_paths_keep_their_order_and_resolve_against_the_config(self) -> None:
        session = config.load_config(self.write(COMPLETE))

        self.assertEqual(
            list(session.dbc_paths),
            [(self.dir / "bus1.dbc").resolve(),
             (self.dir / "bus2.dbc").resolve()])
        self.assertEqual(session.baseline_path,
                         (self.dir / "reference.profile").resolve())

    def test_comments_and_blank_lines_are_ignored(self) -> None:
        path = self.dir / "commented.conf"
        path.write_text("\n# a comment\n\n" + render(COMPLETE) + "\n",
                        encoding="utf-8")

        session = config.load_config(path)

        self.assertEqual(session.window_s, 1.0)

    def test_manifest_reports_values_units_and_the_seed(self) -> None:
        session = config.load_config(self.write(COMPLETE))

        manifest = session.manifest()

        self.assertEqual(manifest["random_seed"], 20260919)
        self.assertEqual(manifest["values"]["window_s"], 1.0)
        self.assertEqual(manifest["units"]["window_s"], "s")
        self.assertEqual(len(manifest["dbc_paths"]), 2)


class MissingParameter(ConfigCase):
    def test_each_parameter_absent_from_the_file_is_an_error(self) -> None:
        for name in config.KNOWN_PARAMETERS:
            values = {key: value for key, value in COMPLETE.items()
                      if key != name}
            with self.subTest(parameter=name):
                with self.assertRaises(config.ConfigError) as caught:
                    config.load_config(self.write(values, f"no_{name}.conf"))
                self.assertIn(name, str(caught.exception))

    def test_the_error_says_that_no_default_is_applied(self) -> None:
        values = {key: value for key, value in COMPLETE.items()
                  if key != "window_s"}

        with self.assertRaises(config.ConfigError) as caught:
            config.load_config(self.write(values))

        message = str(caught.exception)
        self.assertIn("window_s", message)
        self.assertIn("no default", message)

    def test_an_empty_value_is_not_treated_as_an_absent_parameter(self) -> None:
        path = self.dir / "empty_value.conf"
        path.write_text(render(self.variant(window_s="1.0")).replace(
            "window_s = 1.0", "window_s ="), encoding="utf-8")

        with self.assertRaises(config.ConfigError) as caught:
            config.load_config(path)

        self.assertIn("window_s", str(caught.exception))


class OutOfRange(ConfigCase):
    def test_a_value_below_or_above_the_range_is_rejected_by_name(self) -> None:
        cases = {
            "window_s": ("0.0", "3600.0"),
            "sigma_multiplier": ("0.1", "100.0"),
            "missing_frame_multiplier": ("1.0", "1000.0"),
            "min_interval_observations": ("1", "10000000"),
            "burst_min_frames": ("1", "100000"),
            "match_tolerance_s": ("-0.5", "600.0"),
            "random_seed": ("-1", str(2 ** 32)),
        }
        for name, (below, above) in cases.items():
            for value in (below, above):
                with self.subTest(parameter=name, value=value):
                    with self.assertRaises(config.ConfigError) as caught:
                        config.load_config(
                            self.write(self.variant(**{name: value}),
                                       f"range_{name}_{value}.conf"))
                    message = str(caught.exception)
                    self.assertIn(name, message)
                    self.assertIn("out of range", message)

    def test_values_at_the_bounds_are_accepted(self) -> None:
        session = config.load_config(self.write(self.variant(
            window_s="0.001", match_tolerance_s="0.0",
            min_interval_observations="2", random_seed="0")))

        self.assertEqual(session.window_s, 0.001)
        self.assertEqual(session.match_tolerance_s, 0.0)
        self.assertEqual(session.min_interval_observations, 2)
        self.assertEqual(session.random_seed, 0)

    def test_a_non_numeric_or_non_integer_value_is_rejected(self) -> None:
        for name, value in (("window_s", "one second"),
                            ("random_seed", "3.5"),
                            ("window_s", "inf")):
            with self.subTest(parameter=name, value=value):
                with self.assertRaises(config.ConfigError) as caught:
                    config.load_config(self.write(
                        self.variant(**{name: value}),
                        f"bad_{name}_{value.replace(' ', '_')}.conf"))
                self.assertIn(name, str(caught.exception))


class Malformed(ConfigCase):
    def test_an_unknown_parameter_is_rejected_rather_than_ignored(self) -> None:
        with self.assertRaises(config.ConfigError) as caught:
            config.load_config(self.write(self.variant(window_sec="1.0")))

        self.assertIn("window_sec", str(caught.exception))

    def test_a_repeated_single_valued_parameter_is_rejected(self) -> None:
        path = self.dir / "repeated.conf"
        path.write_text(render(COMPLETE) + "window_s = 2.0\n",
                        encoding="utf-8")

        with self.assertRaises(config.ConfigError) as caught:
            config.load_config(path)

        self.assertIn("window_s", str(caught.exception))

    def test_a_line_without_an_assignment_is_rejected(self) -> None:
        path = self.dir / "garbage.conf"
        path.write_text(render(COMPLETE) + "window length one second\n",
                        encoding="utf-8")

        with self.assertRaises(config.ConfigError):
            config.load_config(path)

    def test_a_configuration_file_that_does_not_exist_is_reported(self) -> None:
        with self.assertRaises(config.ConfigError):
            config.load_config(self.dir / "absent.conf")


class Checksums(ConfigCase):
    def test_digests_match_the_bytes_of_the_files_that_were_used(self) -> None:
        path = self.write(COMPLETE)
        session = config.load_config(path)

        digests = session.checksums()

        # The configuration itself, both DBC files and the baseline profile.
        self.assertEqual(len(digests), 4)
        self.assertEqual([digest.parameter for digest in digests],
                         ["config", "dbc_path", "dbc_path", "baseline_path"])
        for digest in digests:
            payload = digest.path.read_bytes()
            self.assertEqual(digest.algorithm, "sha256")
            self.assertEqual(digest.digest, hashlib.sha256(payload).hexdigest())
            self.assertEqual(digest.size_bytes, len(payload))

    def test_editing_an_input_file_changes_its_digest(self) -> None:
        session = config.load_config(self.write(COMPLETE))
        before = {d.parameter + str(d.path): d.digest
                  for d in session.checksums()}

        (self.dir / "bus1.dbc").write_text("BO_ 2 edited\n", encoding="utf-8")
        after = {d.parameter + str(d.path): d.digest
                 for d in session.checksums()}

        changed = [key for key in before if before[key] != after[key]]
        self.assertEqual(len(changed), 1)
        self.assertIn("bus1.dbc", changed[0])

    def test_a_missing_input_file_is_reported_with_its_parameter(self) -> None:
        session = config.load_config(self.write(COMPLETE))
        (self.dir / "reference.profile").unlink()

        with self.assertRaises(config.ConfigError) as caught:
            session.checksums()

        self.assertIn("baseline_path", str(caught.exception))

    def test_loading_does_not_require_the_input_files_to_exist(self) -> None:
        path = self.write(COMPLETE)
        (self.dir / "reference.profile").unlink()

        session = config.load_config(path)

        self.assertEqual(session.baseline_path,
                         (self.dir / "reference.profile").resolve())


class Copy(ConfigCase):
    """The copy stored with the results, criterion 11.3.

    The destination comes from can_detect/session.py so that the copy is named by
    the same rule as the trace and the report, rather than by a second convention
    living here.
    """

    def destination(self, results: Path) -> Path:
        return results / session_names.artefact_name("20260919_120000", "config")

    def test_the_stored_copy_is_byte_for_byte_the_file_that_was_read(self) -> None:
        path = self.dir / "session.conf"
        original = ("# why 1 s: 10 to 100 frames per identifier\n"
                    + render(COMPLETE)).encode("utf-8")
        path.write_bytes(original)
        loaded = config.load_config(path)

        destination = loaded.write_copy(self.destination(self.dir / "results"))

        self.assertEqual(destination.read_bytes(), original)
        self.assertIn("why 1 s", destination.read_text(encoding="utf-8"))
        self.assertIn("20260919_120000", destination.name)

    def test_an_existing_copy_is_left_untouched(self) -> None:
        loaded = config.load_config(self.write(COMPLETE))
        target = self.destination(self.dir / "results")
        first = loaded.write_copy(target)
        first.write_bytes(b"# copy of an earlier session\n")

        with self.assertRaises(config.ConfigError):
            loaded.write_copy(target)

        self.assertEqual(first.read_bytes(), b"# copy of an earlier session\n")


class ExampleFile(unittest.TestCase):
    """The recommended values live in a file, not in the code.

    The distinction is the point of criterion 11.2: 1 s and 3 reach a session
    because a file says so, and the program has no notion of them otherwise.
    """

    def test_the_example_parses_and_carries_the_recommended_values(self) -> None:
        session = config.load_config(config.EXAMPLE_CONFIG_PATH)

        self.assertEqual(session.window_s, 1.0)
        self.assertEqual(session.sigma_multiplier, 3.0)
        self.assertEqual(session.min_interval_observations, 100)

    def test_the_example_points_at_the_dbc_of_the_test_bench(self) -> None:
        session = config.load_config(config.EXAMPLE_CONFIG_PATH)

        self.assertEqual(len(session.dbc_paths), 1)
        self.assertTrue(session.dbc_paths[0].is_file(),
                        f"DBC missing: {session.dbc_paths[0]}")

    def test_no_recommended_value_is_reachable_as_a_default(self) -> None:
        names = [name for name in dir(config)
                 if "DEFAULT" in name.upper()]
        self.assertEqual(names, [])


if __name__ == "__main__":
    unittest.main(verbosity=2)
