"""Decoder for the binary CAN record stream produced by the STM32 logger.

This module mirrors can_logger/Core/Src/can_stream_codec.c byte for byte. The agreement
between the two implementations is verified by test_vectors.py, which decodes a
stream generated by the C encoder itself.

Wire format, little endian throughout:
  every record is COBS encoded and terminated by a single 0x00 byte, the last
  byte of a decoded record is a CRC-8 (polynomial 0x07, initial value 0x00) over
  all preceding bytes, and the first three bytes are always the record type
  followed by the 16-bit sequence number.
"""

from __future__ import annotations

import struct
from dataclasses import dataclass, field
from typing import Iterator, Optional

PROTO_VERSION = 1
MAX_RECORD = 128
MAX_ENCODED = MAX_RECORD + 3
MIN_RECORD = 4

REC_FRAME = 0x01
REC_TIME_SYNC = 0x02
REC_SESSION = 0x03
REC_EVENT = 0x04
REC_BUS_STATS = 0x05
REC_LOGGER_STATS = 0x06
REC_ACK = 0x07
REC_ANALOG_AGG = 0x20  # reserved for CANH/CANL aggregates

LEN_FRAME_BASE = 10
LEN_TIME_SYNC = 12
LEN_SESSION = 43
LEN_EVENT = 25
LEN_BUS_STATS = 111
LEN_LOGGER_STATS = 49
LEN_ACK = 18

FLAG_MEASUREMENT_MODE = 1 << 0
FLAG_USB_LOGGING = 1 << 1
FLAG_STREAM_ENABLED = 1 << 2

EVENT_REASONS = {
    0: "rx_read_error",
    1: "extended_frame_rejected",
    2: "remote_frame_rejected",
    3: "invalid_dlc",
    4: "ring_drop",
    5: "fifo_full",
    6: "fifo_overrun",
    7: "controller_error",
    8: "state_change",
    9: "tx_buffer_overflow",
    10: "usb_log_boundary",
    11: "extended_id_remapped",
}

BUS_STATES = {0: "active", 1: "warning", 2: "passive", 3: "bus_off"}

FRAME_ID_UNKNOWN = 0xFFFF

BUS_STATS_COUNTERS = (
    "rx_frames",
    "valid_frames",
    "buffered_frames",
    "payload_bytes",
    "rx_read_errors",
    "extended_frames",
    "remote_frames",
    "invalid_dlc",
    "fifo_full",
    "fifo_overrun",
    "ring_dropped",
    "warning_entries",
    "passive_entries",
    "bus_off_entries",
    "stuff_errors",
    "form_errors",
    "ack_errors",
    "bit_recessive_errors",
    "bit_dominant_errors",
    "crc_errors",
    "other_errors",
    "last_error_code",
    "last_ring_drop_id",
)


def crc8(data: bytes) -> int:
    """CRC-8, polynomial 0x07, initial value 0x00, no reflection."""
    crc = 0
    for byte in data:
        crc ^= byte
        for _ in range(8):
            if crc & 0x80:
                crc = ((crc << 1) ^ 0x07) & 0xFF
            else:
                crc = (crc << 1) & 0xFF
    return crc


def cobs_encode(payload: bytes) -> bytes:
    """Encodes a record and appends the 0x00 delimiter."""
    out = bytearray()
    code_index = 0
    out.append(0)
    code = 1
    for byte in payload:
        if byte != 0:
            out.append(byte)
            code += 1
        if byte == 0 or code == 0xFF:
            out[code_index] = code
            code_index = len(out)
            out.append(0)
            code = 1
    out[code_index] = code
    out.append(0)
    return bytes(out)


def cobs_decode(encoded: bytes) -> Optional[bytes]:
    """Returns the decoded record, or None when the framing is inconsistent."""
    out = bytearray()
    read = 0
    length = len(encoded)
    while read < length:
        code = encoded[read]
        read += 1
        if code == 0:
            return None
        span = code - 1
        if read + span > length:
            return None
        out.extend(encoded[read:read + span])
        read += span
        if code != 0xFF and read < length:
            out.append(0)
    return bytes(out)


def restore_time(sync_ts64: int, frame_ts32: int) -> int:
    """Rebuilds the 64-bit device time from a 32-bit field.

    The difference is treated as signed, so a frame stamped shortly before the
    synchronisation record is reconstructed correctly too.
    """
    delta = (frame_ts32 - (sync_ts64 & 0xFFFFFFFF)) & 0xFFFFFFFF
    if delta >= 0x80000000:
        delta -= 0x100000000
    return sync_ts64 + delta


@dataclass
class Frame:
    seq: int
    channel: int
    can_id: int
    dlc: int
    data: bytes
    ts32: int
    ts64: Optional[int] = None  # filled in once a time sync is known


@dataclass
class Record:
    type: int
    seq: int
    payload: bytes

    @property
    def known(self) -> bool:
        return self.type in (
            REC_FRAME,
            REC_TIME_SYNC,
            REC_SESSION,
            REC_EVENT,
            REC_BUS_STATS,
            REC_LOGGER_STATS,
            REC_ACK,
        )


@dataclass
class DecoderCounters:
    records_ok: int = 0
    crc_errors: int = 0
    cobs_errors: int = 0
    short_records: int = 0
    sync_losses: int = 0
    unknown_types: int = 0
    bytes_in: int = 0

    def as_dict(self) -> dict:
        return {
            "records_ok": self.records_ok,
            "crc_errors": self.crc_errors,
            "cobs_errors": self.cobs_errors,
            "short_records": self.short_records,
            "sync_losses": self.sync_losses,
            "unknown_types": self.unknown_types,
            "bytes_in": self.bytes_in,
        }


class StreamDecoder:
    """Byte oriented decoder, tolerant of garbage and partial records."""

    def __init__(self) -> None:
        self._buffer = bytearray()
        self._overflow = False
        self.counters = DecoderCounters()

    def feed(self, chunk: bytes) -> Iterator[Record]:
        self.counters.bytes_in += len(chunk)
        for byte in chunk:
            if byte != 0x00:
                if len(self._buffer) < MAX_ENCODED:
                    self._buffer.append(byte)
                else:
                    self._overflow = True
                continue

            if self._overflow:
                self.counters.sync_losses += 1
                self._buffer.clear()
                self._overflow = False
                continue
            if not self._buffer:
                continue

            encoded = bytes(self._buffer)
            self._buffer.clear()

            decoded = cobs_decode(encoded)
            if decoded is None:
                self.counters.cobs_errors += 1
                continue
            if len(decoded) < MIN_RECORD:
                self.counters.short_records += 1
                continue
            if crc8(decoded[:-1]) != decoded[-1]:
                self.counters.crc_errors += 1
                continue

            record = Record(
                type=decoded[0],
                seq=int.from_bytes(decoded[1:3], "little"),
                payload=decoded,
            )
            self.counters.records_ok += 1
            if not record.known:
                self.counters.unknown_types += 1
            yield record


def decode_frame(record: Record) -> Optional[Frame]:
    if record.type != REC_FRAME or len(record.payload) < LEN_FRAME_BASE:
        return None
    seq, idc, ts32 = struct.unpack_from("<HHI", record.payload, 1)
    dlc = (idc >> 11) & 0x0F
    if dlc > 8 or len(record.payload) != LEN_FRAME_BASE + dlc:
        return None
    return Frame(
        seq=seq,
        channel=((idc >> 15) & 0x01) + 1,
        can_id=idc & 0x7FF,
        dlc=dlc,
        data=bytes(record.payload[9:9 + dlc]),
        ts32=ts32,
    )


def decode_time_sync(record: Record) -> Optional[int]:
    if record.type != REC_TIME_SYNC or len(record.payload) != LEN_TIME_SYNC:
        return None
    return struct.unpack_from("<Q", record.payload, 3)[0]


def decode_session(record: Record) -> Optional[dict]:
    if record.type != REC_SESSION or len(record.payload) != LEN_SESSION:
        return None
    (proto, flags, max_len, ts64, can1_bitrate, can2_bitrate, can1_btr,
     can2_btr, uart_baud, rtc_valid, year, month, day, hour, minute,
     second) = struct.unpack_from("<BBHQIIIIIBBBBBBB", record.payload, 3)
    return {
        "proto_version": proto,
        "flags": flags,
        "measurement_mode": bool(flags & FLAG_MEASUREMENT_MODE),
        "usb_logging": bool(flags & FLAG_USB_LOGGING),
        "stream_enabled": bool(flags & FLAG_STREAM_ENABLED),
        "max_record_len": max_len,
        "ts64": ts64,
        "can1_bitrate": can1_bitrate,
        "can2_bitrate": can2_bitrate,
        "can1_btr": can1_btr,
        "can2_btr": can2_btr,
        "uart_baudrate": uart_baud,
        "rtc_valid": bool(rtc_valid),
        "rtc": f"20{year:02d}-{month:02d}-{day:02d} "
               f"{hour:02d}:{minute:02d}:{second:02d}",
    }


def decode_event(record: Record) -> Optional[dict]:
    if record.type != REC_EVENT or len(record.payload) != LEN_EVENT:
        return None
    (channel, reason, state, frame_id, error_code, suppressed,
     ts64) = struct.unpack_from("<BBBHIIQ", record.payload, 3)
    return {
        "channel": channel,
        "reason": reason,
        "reason_name": EVENT_REASONS.get(reason, f"unknown_{reason}"),
        "state": state,
        "state_name": BUS_STATES.get(state, f"unknown_{state}"),
        "frame_id": None if frame_id == FRAME_ID_UNKNOWN else frame_id,
        "error_code": error_code,
        "suppressed": suppressed,
        "ts64": ts64,
    }


def decode_bus_stats(record: Record) -> Optional[dict]:
    if record.type != REC_BUS_STATS or len(record.payload) != LEN_BUS_STATS:
        return None
    channel, ts64 = struct.unpack_from("<BQ", record.payload, 3)
    values = struct.unpack_from("<23I", record.payload, 12)
    (fifo_max_fill, current_rec, current_tec, max_rec, max_tec,
     state) = struct.unpack_from("<6B", record.payload, 104)
    result = {"channel": channel, "ts64": ts64}
    result.update(dict(zip(BUS_STATS_COUNTERS, values)))
    result.update({
        "fifo_max_fill": fifo_max_fill,
        "current_rec": current_rec,
        "current_tec": current_tec,
        "max_rec": max_rec,
        "max_tec": max_tec,
        "state": state,
        "state_name": BUS_STATES.get(state, f"unknown_{state}"),
    })
    return result


def decode_logger_stats(record: Record) -> Optional[dict]:
    if (record.type != REC_LOGGER_STATS
            or len(record.payload) != LEN_LOGGER_STATS):
        return None
    (ts64, ring_drop_total, tx_records_sent, tx_bytes_sent,
     tx_records_dropped, tx_bytes_dropped, event_queue_dropped, loop_max_us,
     ring_peak, ring_capacity, tx_buffer_peak, tx_buffer_capacity,
     flags) = struct.unpack_from("<QIIIIIIIHHHHB", record.payload, 3)
    return {
        "ts64": ts64,
        "ring_drop_total": ring_drop_total,
        "tx_records_sent": tx_records_sent,
        "tx_bytes_sent": tx_bytes_sent,
        "tx_records_dropped": tx_records_dropped,
        "tx_bytes_dropped": tx_bytes_dropped,
        "event_queue_dropped": event_queue_dropped,
        "loop_max_us": loop_max_us,
        "ring_peak": ring_peak,
        "ring_capacity": ring_capacity,
        "tx_buffer_peak": tx_buffer_peak,
        "tx_buffer_capacity": tx_buffer_capacity,
        "flags": flags,
        "measurement_mode": bool(flags & FLAG_MEASUREMENT_MODE),
        "usb_logging": bool(flags & FLAG_USB_LOGGING),
        "stream_enabled": bool(flags & FLAG_STREAM_ENABLED),
    }


def decode_ack(record: Record) -> Optional[dict]:
    if record.type != REC_ACK or len(record.payload) != LEN_ACK:
        return None
    status, command, value, ts64 = struct.unpack_from(
        "<BBIQ", record.payload, 3)
    return {
        "status": status,
        "accepted": status == 0,
        "command": command,
        "value": value,
        "ts64": ts64,
    }


@dataclass
class SequenceTracker:
    """Tracks gaps in the 16-bit stream sequence number.

    A gap means records lost on the serial link. Frames dropped inside the
    logger never consume a sequence number, they are reported through the
    counters instead, so the two causes stay distinguishable.
    """

    expected: Optional[int] = None
    gaps: list = field(default_factory=list)
    missing_total: int = 0

    def observe(self, seq: int, ts64: Optional[int]) -> int:
        if self.expected is None:
            self.expected = (seq + 1) & 0xFFFF
            return 0
        missing = (seq - self.expected) & 0xFFFF
        if missing != 0:
            if missing > 0x8000:
                # Sequence went backwards, which points at a device restart.
                missing = 0
            else:
                self.gaps.append({
                    "after_seq": (self.expected - 1) & 0xFFFF,
                    "next_seq": seq,
                    "missing": missing,
                    "ts64": ts64,
                })
                self.missing_total += missing
        self.expected = (seq + 1) & 0xFFFF
        return missing
