"""Detection rules driven by CAN-controller protocol diagnostics.

The logger reports cumulative counters in BUS_STATS records.  This module
turns their already reconstructed deltas (added by :mod:`can_detect.trace`)
into anomaly events.  State is kept per CAN channel, because the logger emits
one statistics stream for each controller.

The public convenience function accepts the same iterable of ``TraceRecord``
objects as the other detection stages::

    events = detect_protocol_layer(records)

Events are plain dictionaries so they can be passed directly to the reporting
layer.  A loss event carries the interval object from the statistics record and
also forces that interval to be incomplete.  The latter is deliberately done
here as well as in ``TraceReader``: callers may feed a decoded record produced
by another source and must not be able to evaluate a loss interval as complete.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Iterable, Iterator, Optional

from . import trace

# These are the six protocol error classes named by requirement 6.1.  The
# spelling is the wire/protocol spelling and is kept stable in reports.
PROTOCOL_ERROR_COUNTERS = (
    "stuff_errors",
    "form_errors",
    "ack_errors",
    "bit_recessive_errors",
    "bit_dominant_errors",
    "crc_errors",
)

# ``TraceReader`` uses this same set for interval completeness.  Include read
# errors too: although they are not a protocol error class, they represent a
# lost record in the device input path and therefore make the interval unsafe.
DEVICE_LOSS_COUNTERS = tuple(trace.BUS_LOSS_COUNTER_FIELDS)

TARGET_CONTROLLER_STATES = {"warning", "passive", "bus_off"}

# These event reasons mean that the controller received a frame but the
# firmware could not represent it as a normal 11-bit data-frame record.
# They are event records rather than cumulative statistics, so each decoded
# event is reported separately.  The suppressed field still exposes any
# additional occurrences hidden by firmware rate limiting.
REJECTED_FRAME_REASONS = {
    1: "extended_frame_rejected",
    2: "remote_frame_rejected",
    3: "invalid_dlc",
}

# A CAN ID is trustworthy for loss attribution only when the firmware rejected
# the frame while moving it into the RAM ring buffer.  Protocol errors identify
# an incomplete/corrupted transmission, and receive FIFO overflow reports only
# a count, so neither may expose an identifier in an anomaly event.
RAM_BUFFER_LOSS_COUNTER = "ring_dropped"
FRAME_ID_SOURCE_RAM_BUFFER = "ram_buffer_rejection"
FRAME_ID_SOURCE_UNTRUSTED = "untrusted"


def _event(event_type: str, *, ts64: Optional[int], channel: int,
           **fields: object) -> dict:
    """Create the common, JSON-serialisable anomaly event shape."""
    result = {
        "type": event_type,
        "method": "protocol_layer",
        "ts64": ts64,
        "channel": channel,
    }
    result.update(fields)
    return result


def _mark_incomplete(interval: Optional[dict], reason: str = "device_loss") -> None:
    """Mark an interval incomplete without duplicating its reason."""
    if interval is None:
        return
    interval["complete"] = False
    reasons = interval.setdefault("reasons", [])
    if reason not in reasons:
        reasons.append(reason)


@dataclass
class ProtocolLayerDetector:
    """Incremental detector for protocol-layer alarms.

    The first statistics sample on each channel establishes the controller
    state baseline.  It cannot describe a transition or a counter increment,
    because no preceding sample is available.  Subsequent samples use the
    deltas prepared by ``TraceReader``; consequently counter wrap-around is
    handled once, at the trace boundary, rather than being reinterpreted here.
    """

    _last_state: dict[int, str] = field(default_factory=dict)
    events: list[dict] = field(default_factory=list)

    def process(self, record: trace.TraceRecord) -> list[dict]:
        """Process one record and return alarms generated by that record."""
        if record.type == trace.proto.REC_EVENT:
            event = record.decoded
            if not isinstance(event, dict):
                return []
            reason = int(event.get("reason", -1))
            reason_name = REJECTED_FRAME_REASONS.get(reason)
            if reason_name is None:
                return []
            channel = int(event.get("channel", 0))
            generated = [_event(
                "frame_profile_mismatch", ts64=event.get("ts64"),
                channel=channel,
                rejection_reason=reason_name,
                # Rejected-frame diagnostics are not data-loss attribution:
                # the ID may belong to an invalid or partially received frame.
                frame_id=None,
                frame_id_source=FRAME_ID_SOURCE_UNTRUSTED,
                error_code=int(event.get("error_code", 0)),
                suppressed=int(event.get("suppressed", 0)),
                rejected_events=1 + int(event.get("suppressed", 0)),
            )]
            self.events.extend(generated)
            return generated

        if record.type != trace.proto.REC_BUS_STATS:
            return []
        stats = record.decoded
        if not isinstance(stats, dict):
            return []

        channel = int(stats["channel"])
        generated: list[dict] = []
        increments = stats.get("counter_increments")

        # The first sample has no delta.  It still establishes the state
        # baseline, preventing a boot-time warning state from being reported
        # as a change.
        if isinstance(increments, dict):
            for counter in PROTOCOL_ERROR_COUNTERS:
                delta = int(increments.get(counter, 0))
                if delta > 0:
                    generated.append(_event(
                        "protocol_error", ts64=stats.get("ts64"),
                        channel=channel, error_class=counter,
                        increment=delta,
                        frame_id=None,
                        frame_id_source=FRAME_ID_SOURCE_UNTRUSTED,
                    ))

            losses = {
                counter: int(increments.get(counter, 0))
                for counter in DEVICE_LOSS_COUNTERS
                if int(increments.get(counter, 0)) > 0
            }
            if losses:
                interval = stats.get("interval")
                _mark_incomplete(interval)
                ring_drop_delta = int(losses.get(RAM_BUFFER_LOSS_COUNTER, 0))
                frame_id = (int(stats.get("last_ring_drop_id"))
                            if ring_drop_delta > 0 else None)
                frame_id_source = (FRAME_ID_SOURCE_RAM_BUFFER
                                   if ring_drop_delta > 0
                                   else FRAME_ID_SOURCE_UNTRUSTED)
                generated.append(_event(
                    "device_frame_loss", ts64=stats.get("ts64"),
                    channel=channel, loss_increments=losses,
                    interval=interval, frame_id=frame_id,
                    frame_id_source=frame_id_source,
                ))

        state = str(stats.get("state_name", "unknown"))
        previous_state = self._last_state.get(channel)
        if (previous_state is not None and state != previous_state
                and state in TARGET_CONTROLLER_STATES):
            generated.append(_event(
                "controller_state_change", ts64=stats.get("ts64"),
                channel=channel, state=state,
                previous_state=previous_state,
                rec=int(stats.get("current_rec", 0)),
                tec=int(stats.get("current_tec", 0)),
            ))
        self._last_state[channel] = state
        self.events.extend(generated)
        return generated

    def process_all(self, records: Iterable[trace.TraceRecord]) -> Iterator[dict]:
        """Yield alarms while consuming records in trace order."""
        for record in records:
            yield from self.process(record)


def detect_protocol_layer(records: Iterable[trace.TraceRecord]) -> list[dict]:
    """Return protocol-layer alarms for an iterable of enriched records."""
    detector = ProtocolLayerDetector()
    return list(detector.process_all(records))


__all__ = [
    "DEVICE_LOSS_COUNTERS",
    "FRAME_ID_SOURCE_RAM_BUFFER",
    "FRAME_ID_SOURCE_UNTRUSTED",
    "PROTOCOL_ERROR_COUNTERS",
    "ProtocolLayerDetector",
    "detect_protocol_layer",
]
